import { useContext, useMemo, useState, useEffect, useRef } from 'react';
import { AppContext } from '../context/AppContext';
import { Sparkles, Brain, AlertCircle, CheckCircle, Activity, Target, GitMerge, FastForward, Send, User, Bot, Loader2 } from 'lucide-react';
import { ROLES, getWorkingDaysElapsed } from '../constants';
import { computeCriticalChain } from '../utils/criticalChain';

export const AIInsights = () => {
  const { tasks, projects, users, currentUser } = useContext(AppContext);

  const isOverall = [ROLES.MANAGEMENT, ROLES.RD_HEAD, ROLES.PM].includes(currentUser.role);
  
  const insightsData = useMemo(() => {
    let relevantTasks: any[];
    let relevantProjects: any[];
    let departmentName = '';

    if (isOverall) {
      relevantTasks = tasks;
      relevantProjects = projects;
    } else {
      departmentName = currentUser.department || 'Your Department';
      const deptUsers = users.filter((u: any) => u.department === currentUser.department);
      const deptUserIds = deptUsers.map((u: any) => u.id);

      relevantTasks = tasks.filter((t: any) => {
        if (!t.assignedTo) return false;
        if (Array.isArray(t.assignedTo)) {
          return t.assignedTo.some((id: string) => deptUserIds.includes(id));
        }
        return deptUserIds.includes(t.assignedTo);
      });

      const projectIds = new Set(relevantTasks.map((t: any) => t.projectId));
      relevantProjects = projects.filter((p: any) => projectIds.has(p.id));
    }

    const totalTasks = relevantTasks.length;
    const completedTasks = relevantTasks.filter((t: any) => t.status === 'Completed');
    const pendingTasks = relevantTasks.filter((t: any) => t.status === 'Pending Start');
    
    const now = new Date();
    const runningTasks = relevantTasks.filter((t: any) => t.startedAt && t.status !== 'Completed');
    const overdueTasks = runningTasks.filter((t: any) => {
      const start = new Date(t.startedAt);
      const assigned = t.assignedDays || 0;
      const elapsed = getWorkingDaysElapsed(start, now);
      return elapsed > assigned;
    });

    const activeProjects = relevantProjects.filter((p: any) => p.status !== 'Completed').length;

    // Advanced CCPM Logic
    // Compute critical chain for all projects in context
    const chainMap = computeCriticalChain(relevantTasks);
    const criticalTasks = relevantTasks.filter((t: any) => chainMap.get(String(t.id)) === 'Critical');
    const feedingTasks = relevantTasks.filter((t: any) => chainMap.get(String(t.id)) === 'Feeding');

    // Find next tasks to start (Pending, but all predecessors are complete)
    const nextToStart = pendingTasks.filter((t: any) => {
      if (!t.predecessors || t.predecessors.length === 0) return true;
      const uncompletedPreds = t.predecessors.filter((pId: string) => {
        const pred = tasks.find((pt: any) => String(pt.id) === String(pId));
        return pred && pred.status !== 'Completed';
      });
      return uncompletedPreds.length === 0;
    });

    return {
      totalTasks,
      completedCount: completedTasks.length,
      runningCount: runningTasks.length,
      activeProjects,
      overdueCount: overdueTasks.length,
      criticalCount: criticalTasks.length,
      feedingCount: feedingTasks.length,
      nextToStartCount: nextToStart.length,
      nextToStartTasks: nextToStart.slice(0, 3), // Top 3
      departmentName: isOverall ? 'Overall Organization' : departmentName,
      relevantTasks,
      relevantProjects
    };
  }, [tasks, projects, users, currentUser, isOverall]);

  const [backendInsights, setBackendInsights] = useState<{ summaryText: string, actionItems: any[] } | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchInsights = async () => {
      setIsLoading(true);
      try {
        const apiBase = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000") || 'http://localhost:5000/api';
        const response = await fetch(`${apiBase}/ai-insights`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            departmentName: insightsData.departmentName,
            isOverall,
            tasks: insightsData.relevantTasks,
            projects: insightsData.relevantProjects
          })
        });
        
        if (!response.ok) throw new Error('Failed to fetch AI insights');
        
        const dataStr = await response.json();
        let parsedData = dataStr;
        if (typeof dataStr === 'string') {
          try {
             parsedData = JSON.parse(dataStr);
          } catch (e) {
             console.error("Failed to parse inner JSON", e);
          }
        }
        
        setBackendInsights({
           summaryText: parsedData.summaryText || 'Insights successfully generated by AI.',
           actionItems: parsedData.actionItems || []
        });
      } catch (error) {
        console.error("AI Insights error:", error);
        setBackendInsights({
          summaryText: 'Could not connect to AI service. Displaying standard fallback insights.',
          actionItems: []
        });
      } finally {
        setIsLoading(false);
      }
    };
    
    fetchInsights();
  }, [insightsData.relevantTasks, insightsData.relevantProjects, insightsData.departmentName, isOverall]);

  // Chat Agent State
  const [chatMessages, setChatMessages] = useState<{role: 'user'|'assistant', content: string}[]>([
    { role: 'assistant', content: `Hello ${currentUser.name.split(' ')[0]}! I'm Viruj AI. How can I help you analyze your projects and tasks today?` }
  ]);
  const [chatInput, setChatInput] = useState('');
  const [isChatLoading, setIsChatLoading] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [chatMessages]);

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim() || isChatLoading) return;

    const userMessage = chatInput.trim();
    setChatInput('');
    const newMessages = [...chatMessages, { role: 'user' as const, content: userMessage }];
    setChatMessages(newMessages);
    setIsChatLoading(true);

    try {
      const apiBase = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000") || 'http://localhost:5000/api';
      const response = await fetch(`${apiBase}/ai-chat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          departmentName: insightsData.departmentName,
          isOverall,
          tasks: insightsData.relevantTasks,
          projects: insightsData.relevantProjects,
          messages: newMessages.slice(1).map(m => ({ role: m.role, content: m.content })) // exclude initial greeting if desired, or keep it. We map to simple objects.
        })
      });
      
      if (!response.ok) throw new Error('Failed to fetch AI chat response');
      
      const data = await response.json();
      setChatMessages(prev => [...prev, { role: 'assistant', content: data.response }]);
    } catch (error) {
      console.error("AI Chat error:", error);
      setChatMessages(prev => [...prev, { role: 'assistant', content: 'Sorry, I am having trouble connecting to my servers right now.' }]);
    } finally {
      setIsChatLoading(false);
    }
  };


  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-12">
      
      {/* Header Section */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-900 via-[#1e3a5f] to-slate-900 p-8 text-white shadow-2xl">
        <div className="absolute top-0 right-0 -mr-20 -mt-20 opacity-10">
          <Brain className="w-96 h-96" />
        </div>
        <div className="relative z-10 max-w-3xl space-y-4">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-indigo-500/20 rounded-xl backdrop-blur-md border border-indigo-400/30">
              <Sparkles className="w-6 h-6 text-indigo-300" />
            </div>
            <h1 className="text-3xl font-extrabold tracking-tight">AI Insights Engine</h1>
          </div>
          <p className="text-indigo-100/80 text-lg leading-relaxed font-medium">
            Intelligent analysis for <span className="text-white font-bold px-2 py-1 bg-white/10 rounded-lg ml-1">{insightsData.departmentName}</span>
          </p>
          <div className="mt-6 p-4 bg-white/5 border border-white/10 rounded-2xl backdrop-blur-sm min-h-[80px]">
            {isLoading ? (
               <div className="animate-pulse space-y-2">
                 <div className="h-4 bg-white/20 rounded w-3/4"></div>
                 <div className="h-4 bg-white/20 rounded w-1/2"></div>
               </div>
            ) : (
               <p className="text-sm text-indigo-50 leading-relaxed italic">
                 "{backendInsights?.summaryText}"
               </p>
            )}
          </div>
        </div>
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <MetricCard 
          icon={Activity} 
          title="Running Tasks" 
          value={insightsData.runningCount} 
          trend="In Progress"
          color="bg-blue-50 text-blue-600 border-blue-200"
        />
        <MetricCard 
          icon={AlertCircle} 
          title="Delayed Tasks" 
          value={insightsData.overdueCount} 
          trend={insightsData.overdueCount > 0 ? "Requires attention" : "On track"}
          color={insightsData.overdueCount > 0 ? "bg-red-50 text-red-600 border-red-200" : "bg-gray-50 text-gray-600 border-gray-200"}
        />
        <MetricCard 
          icon={CheckCircle} 
          title="Completed Tasks" 
          value={insightsData.completedCount} 
          trend={`Out of ${insightsData.totalTasks}`}
          color="bg-emerald-50 text-emerald-600 border-emerald-200"
        />
        <MetricCard 
          icon={Target} 
          title="Active Projects" 
          value={insightsData.activeProjects} 
          trend="Overall Health"
          color="bg-purple-50 text-purple-600 border-purple-200"
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* CCPM Breakdown Section */}
        <div className="p-8 rounded-3xl bg-white border border-gray-100 shadow-sm relative overflow-hidden">
          <div className="absolute top-0 right-0 p-8 opacity-5">
            <GitMerge className="w-32 h-32" />
          </div>
          <h2 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2 relative z-10">
            <GitMerge className="w-5 h-5 text-indigo-600" /> CCPM Architecture
          </h2>
          <div className="grid grid-cols-2 gap-4 relative z-10">
            <div className="p-4 bg-red-50 rounded-2xl border border-red-100">
              <p className="text-xs font-bold text-red-400 uppercase tracking-wider mb-1">Critical Chain</p>
              <h3 className="text-3xl font-black text-red-600">{insightsData.criticalCount}</h3>
              <p className="text-xs text-red-500 mt-2 font-medium leading-relaxed">Tasks directly impacting the final project deadline.</p>
            </div>
            <div className="p-4 bg-amber-50 rounded-2xl border border-amber-100">
              <p className="text-xs font-bold text-amber-500 uppercase tracking-wider mb-1">Feeding Chain</p>
              <h3 className="text-3xl font-black text-amber-600">{insightsData.feedingCount}</h3>
              <p className="text-xs text-amber-600 mt-2 font-medium leading-relaxed">Tasks buffering the critical path with available float.</p>
            </div>
          </div>
        </div>

        {/* Ready to Start Section */}
        <div className="p-8 rounded-3xl bg-white border border-gray-100 shadow-sm relative overflow-hidden">
          <div className="absolute top-0 right-0 p-8 opacity-5">
            <FastForward className="w-32 h-32" />
          </div>
          <h2 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2 relative z-10">
            <FastForward className="w-5 h-5 text-emerald-600" /> Ready to Start
          </h2>
          <div className="relative z-10 space-y-3">
            {insightsData.nextToStartTasks.length > 0 ? (
              insightsData.nextToStartTasks.map((t: any) => (
                <div key={t.id} className="p-3 bg-emerald-50 rounded-xl border border-emerald-100 flex items-center justify-between">
                  <div>
                    <p className="text-sm font-bold text-emerald-900">{t.title}</p>
                    <p className="text-xs text-emerald-700 mt-0.5">Assigned to: {Array.isArray(t.assignedTo) ? 'Multiple' : 'Team Member'}</p>
                  </div>
                  <div className="px-2 py-1 bg-emerald-200 text-emerald-800 text-xs font-bold rounded-lg">
                    {t.assignedDays || 1} days
                  </div>
                </div>
              ))
            ) : (
              <div className="p-6 text-center border-2 border-dashed border-gray-200 rounded-2xl">
                <p className="text-sm text-gray-500 font-medium">No tasks are currently unblocked and ready to begin.</p>
              </div>
            )}
            {insightsData.nextToStartCount > 3 && (
              <p className="text-xs text-center text-gray-500 font-medium pt-2">
                + {insightsData.nextToStartCount - 3} more tasks ready to start
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Actionable Insights */}
      <div>
        <h2 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2">
          <Brain className="w-5 h-5 text-indigo-600" /> Preventative Recommendations
        </h2>
        <div className="grid gap-4">
          {isLoading ? (
             <div className="p-8 text-center text-gray-500 bg-white border border-gray-200 rounded-2xl animate-pulse">
               Generating real-time AI insights...
             </div>
          ) : (
             <>
                {backendInsights?.actionItems?.map((item, idx) => (
                  <InsightRow key={idx} type={item.type} text={item.text} />
                ))}
                {(!backendInsights?.actionItems || backendInsights.actionItems.length === 0) && (
                  <div className="p-8 text-center text-gray-500 bg-white border border-gray-200 rounded-2xl">
                    No new recommendations at this time.
                  </div>
                )}
             </>
          )}
        </div>
      </div>

      {/* Interactive AI Agent Chat */}
      <div className="mt-8 rounded-3xl bg-white border border-gray-100 shadow-sm overflow-hidden flex flex-col h-[500px]">
        <div className="p-4 bg-gradient-to-r from-indigo-900 to-[#1e3a5f] text-white flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-white/10 rounded-full flex items-center justify-center border border-white/20">
              <Bot className="w-5 h-5 text-indigo-200" />
            </div>
            <div>
              <h2 className="font-bold text-lg leading-tight">Viruj AI Assistant</h2>
              <p className="text-xs text-indigo-200 font-medium">Online & ready to help</p>
            </div>
          </div>
        </div>
        
        <div className="flex-1 overflow-y-auto p-6 bg-gray-50/50 space-y-4">
          {chatMessages.map((msg, idx) => (
            <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-in fade-in duration-300`}>
              <div className={`flex gap-3 max-w-[80%] ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${msg.role === 'user' ? 'bg-blue-100 text-blue-600' : 'bg-indigo-100 text-indigo-600'}`}>
                  {msg.role === 'user' ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
                </div>
                <div className={`p-4 rounded-2xl text-sm leading-relaxed shadow-sm whitespace-pre-wrap ${
                  msg.role === 'user' 
                    ? 'bg-blue-600 text-white rounded-tr-none' 
                    : 'bg-white border border-gray-100 text-gray-800 rounded-tl-none'
                }`}>
                  {msg.content}
                </div>
              </div>
            </div>
          ))}
          {isChatLoading && (
            <div className="flex justify-start animate-in fade-in duration-300">
              <div className="flex gap-3 max-w-[80%] flex-row">
                <div className="w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 bg-indigo-100 text-indigo-600">
                  <Bot className="w-4 h-4" />
                </div>
                <div className="p-4 rounded-2xl text-sm bg-white border border-gray-100 text-gray-800 rounded-tl-none flex items-center gap-2">
                  <Loader2 className="w-4 h-4 animate-spin text-indigo-400" />
                  <span className="text-gray-400 font-medium">Viruj AI is thinking...</span>
                </div>
              </div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>

        <div className="p-4 bg-white border-t border-gray-100">
          <form onSubmit={handleSendMessage} className="flex gap-2">
            <input
              type="text"
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              placeholder="Ask anything about your projects, delays, or critical chains..."
              className="flex-1 p-3 px-4 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500 transition-all text-sm font-medium"
              disabled={isChatLoading}
            />
            <button
              type="submit"
              disabled={!chatInput.trim() || isChatLoading}
              className="px-5 bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 disabled:cursor-not-allowed text-white rounded-xl font-bold transition-colors flex items-center justify-center shadow-md shadow-indigo-600/20"
            >
              <Send className="w-5 h-5" />
            </button>
          </form>
        </div>
      </div>

    </div>
  );
};

const MetricCard = ({ icon: Icon, title, value, trend, color }: any) => (
  <div className={`p-6 rounded-3xl border bg-white shadow-sm hover:shadow-md transition-all duration-300 relative overflow-hidden group`}>
    <div className={`absolute top-0 right-0 w-32 h-32 -mr-8 -mt-8 opacity-[0.03] group-hover:scale-110 transition-transform duration-500 rounded-full ${color.split(' ')[0]}`} />
    
    <div className="flex items-start justify-between relative z-10">
      <div>
        <p className="text-sm font-semibold text-gray-500 mb-1">{title}</p>
        <h3 className="text-3xl font-black text-gray-900">{value}</h3>
      </div>
      <div className={`p-3 rounded-2xl ${color}`}>
        <Icon className="w-6 h-6" />
      </div>
    </div>
    <div className="mt-4 pt-4 border-t border-gray-100 flex items-center gap-2 text-xs font-medium text-gray-500 relative z-10">
      <span className="px-2 py-1 bg-gray-100 rounded-md">{trend}</span>
    </div>
  </div>
);

const InsightRow = ({ type, text }: { type: string, text: string }) => {
  const styles = {
    warning: "bg-orange-50 border-orange-200 text-orange-800",
    success: "bg-emerald-50 border-emerald-200 text-emerald-800",
    info: "bg-blue-50 border-blue-200 text-blue-800"
  };
  const icons = {
    warning: <AlertCircle className="w-5 h-5 text-orange-500" />,
    success: <CheckCircle className="w-5 h-5 text-emerald-500" />,
    info: <Sparkles className="w-5 h-5 text-blue-500" />
  };
  
  const selectedStyle = styles[type as keyof typeof styles] || styles.info;
  const SelectedIcon = icons[type as keyof typeof icons] || icons.info;

  return (
    <div className={`flex items-start gap-4 p-5 rounded-2xl border ${selectedStyle} hover:shadow-md transition-shadow`}>
      <div className="mt-0.5 bg-white/50 p-2 rounded-xl backdrop-blur-sm shadow-sm">
        {SelectedIcon}
      </div>
      <p className="text-sm font-medium leading-relaxed pt-1">
        {text}
      </p>
    </div>
  );
};
